# CxxWrap 0.9 needs a recent gcc
dist: bionic

language: julia
sudo: false
os:
  - linux
#  - osx
julia:
  - 1.0
  - 1.2
  - 1.3
#  - nightly
  
branches:
  only:
  - master

matrix:
  allow_failures:
    - julia: nightly
notifications:
  - email: false
# Use the default script
#script:
#  - julia -e 'using Pkg; Pkg.clone(pwd());'
#  - while sleep 30; do echo "still alive"; done &
#  - julia -e 'using Pkg; Pkg.build("Nemo");'
#  - julia -e 'using Pkg; Pkg.test("Nemo");'

env:
   global:
      - DOCUMENTER_DEBUG=true

jobs:
   include:
     - stage: "Test"
       julia: 1.0
       os: linux
       script:
         - while sleep 30; do echo "still alive"; done &
         - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(path=pwd())); Pkg.instantiate();'
         - julia --project=docs/ docs/make.jl
       after_success: skip
