# CxxWrap 0.9 needs a recent gcc
dist: bionic
language: julia

os:
  - osx
  - linux

julia:
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

env:
  global:
    DOCUMENTER_DEBUG=true

jobs:
# # Uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
  allow_failures:
    - julia: 
      - 1.3
      - nightly
      #1.3 can fail due to gap
  include:
    # also test with latest macOS image and latest Julia
    - julia: 1.4
      os: osx
      osx_image: xcode11.3
      before_script:
        # HACK so slow Polymake build does not abort CI test
        - while sleep 30; do echo "still alive"; done &

    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ --color=yes -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ --color=yes docs/make.jl
      after_success: skip

codecov: true
coveralls: true
