[FTM-1511-03209]
git-tree-sha1 = "2f4789fb56911fa34843c1754042837e07c2d376"
lazy = true

    [[FTM-1511-03209.download]]
    sha256 = "9c2f4f6fa9cab3df70cbb2511e1caf4d8d5c8ddb27f8c3b4ddba1f1b84dc8848"
    url = "https://zenodo.org/records/15548043/files/1511-03209.tar.gz"

[QSMDB]
git-tree-sha1 = "472148e587b9da2c78a9955d0d258fbbfed649de"
lazy = true

     [[QSMDB.download]]
     sha256 = "e77cf0716ec656cc8911f6f520653b309fc84f3735d49d46320c48a820a4af31"
     url = "https://github.com/oscar-system/Oscar.jl/releases/download/archive-tag-1/QSMDB-7.tar.gz"

[gap_extraperfect]
git-tree-sha1 = "084fa12573e5089ceb3299f9d341f244b415da52"
lazy = true

    [[gap_extraperfect.download]]
    sha256 = "e565303927682f54cba20a69b8d23673b9b9d4d2a2bc88751f58ed5d3365e29f"
    url = "https://github.com/oscar-system/GAP.jl/releases/download/archive-tag/extraperfect.tar.gz"
    # Created from https://github.com/hulpke/extraperfect using
    # #!/bin/sh
    # export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
    # rm -rf extraperfect
    # mkdir extraperfect
    # gzip -9 -n -c perf27.grp > extraperfect/perf27.grp.gz
    # gzip -9 -n -c perf33.grp > extraperfect/perf33.grp.gz
    # gtar --mtime="$(git log -1 --pretty=%cI)" --owner=0 --group=0 --numeric-owner -cvf extraperfect.tar extraperfect
    # gzip -n -c extraperfect.tar > extraperfect.tar.gz
