name = "GroebnerWalk"
uuid = "6dc8777d-2b0c-4de5-9e3c-426c1820f6f9"
authors = ["Kamillo Ferry <kafe@kafe.dev>", "Francesco Nowell <francesconowell@gmail.com>"]
version = "1.0.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
