[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
Documenter = "1.12.0"
DocumenterCitations = "~1.3.4"
JSON = "0.21.4"
